language: node_js

node_js:
  - "6.1"

branches:
  only:
    - master

install:
  - npm install -g bower
  - npm install

after_success:
  - git push https://$DEPLOY_USER@$DEPLOY_PWD@$DEPLOY_URL master
