language: node_js

node_js:
  - "6.1"

branches:
  only:
    - master

install:
  - npm install -g bower
  - npm install

after_success:
  - git remote add production $DEPLOY_REMOTE
  - git push production master
