language: node_js

node_js:
- '6.1'

branches:
  only:
  - master

install:
- npm install -g bower
- npm install

deploy:
  provider: azure_web_apps
  username: AZURE_WA_USERNAME
  password: AZURE_WA_PASSWORD
  site: AZURE_WA_SITE
